# example netlify.toml
[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

[context.production]
  environment = { PUBLIC_API_DOMAIN = "https://hungryhub.com", NODE_VERSION = "16.16.0" }